"""add-receipt-tables

Revision ID: 20251126_1721
Revises: 20251126_1225
Create Date: 2025-11-26 17:21:53.971780

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# Relationship added in @app/modules/user/model.py:
# -----
# from sqlalchemy.orm import relationship
# ...
# receipts = relationship(
#     "Receipt",
#     back_populates="user"
# )
# -----

# revision identifiers, used by Alembic.
revision: str = '20251126_1721'
down_revision: Union[str, Sequence[str], None] = '20251126_1225'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('receipt',
    sa.Column('subtotal', sa.Float(), nullable=False),
    sa.Column('tax', sa.Float(), nullable=True),
    sa.Column('service_charge', sa.Float(), nullable=True),
    sa.Column('tip', sa.Float(), nullable=True),
    sa.Column('rounding_amount', sa.Float(), nullable=True),
    sa.Column('discount', sa.Float(), nullable=True),
    sa.Column('total_amount', sa.Float(), nullable=False),
    sa.Column('receipt_url', sa.String(), nullable=True),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('restaurant_name', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_receipt_user_id'), 'receipt', ['user_id'], unique=False)
    op.create_table('receipt_item',
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('unit_price', sa.Float(), nullable=False),
    sa.Column('total_price', sa.Float(), nullable=False),
    sa.Column('receipt_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['receipt_id'], ['receipt.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_receipt_item_receipt_id'), 'receipt_item', ['receipt_id'], unique=False)
    op.create_table('receipt_participant',
    sa.Column('is_owner', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('owes_amount', sa.Float(), nullable=True),
    sa.Column('split_method', sa.Enum('equal', 'weighted', name='splitmethod'), server_default='weighted', nullable=False),
    sa.Column('receipt_id', sa.UUID(), nullable=False),
    sa.Column('participant_type', sa.Enum('user', 'external', name='participanttype'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('external_contact_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['external_contact_id'], ['external_contact.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['receipt_id'], ['receipt.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_receipt_participant_external_contact_id'), 'receipt_participant', ['external_contact_id'], unique=False)
    op.create_index(op.f('ix_receipt_participant_receipt_id'), 'receipt_participant', ['receipt_id'], unique=False)
    op.create_index(op.f('ix_receipt_participant_user_id'), 'receipt_participant', ['user_id'], unique=False)
    op.create_table('receipt_item_friend',
    sa.Column('item_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('external_contact_id', sa.UUID(), nullable=True),
    sa.Column('share_ratio', sa.Float(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['external_contact_id'], ['external_contact.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['item_id'], ['receipt_item.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_receipt_item_friend_external_contact_id'), 'receipt_item_friend', ['external_contact_id'], unique=False)
    op.create_index(op.f('ix_receipt_item_friend_item_id'), 'receipt_item_friend', ['item_id'], unique=False)
    op.create_index(op.f('ix_receipt_item_friend_user_id'), 'receipt_item_friend', ['user_id'], unique=False)
    op.create_table('receipt_item_variation',
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('item_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['item_id'], ['receipt_item.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_receipt_item_variation_item_id'), 'receipt_item_variation', ['item_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_receipt_item_variation_item_id'), table_name='receipt_item_variation')
    op.drop_table('receipt_item_variation')
    op.drop_index(op.f('ix_receipt_item_friend_user_id'), table_name='receipt_item_friend')
    op.drop_index(op.f('ix_receipt_item_friend_item_id'), table_name='receipt_item_friend')
    op.drop_index(op.f('ix_receipt_item_friend_external_contact_id'), table_name='receipt_item_friend')
    op.drop_table('receipt_item_friend')
    op.drop_index(op.f('ix_receipt_participant_user_id'), table_name='receipt_participant')
    op.drop_index(op.f('ix_receipt_participant_receipt_id'), table_name='receipt_participant')
    op.drop_index(op.f('ix_receipt_participant_external_contact_id'), table_name='receipt_participant')
    op.drop_table('receipt_participant')
    op.drop_index(op.f('ix_receipt_item_receipt_id'), table_name='receipt_item')
    op.drop_table('receipt_item')
    op.drop_index(op.f('ix_receipt_user_id'), table_name='receipt')
    op.drop_table('receipt')
    # ### end Alembic commands ###

    # Drop the enum types created for this migration.
    op.execute("DROP TYPE IF EXISTS splitmethod;")
    op.execute("DROP TYPE IF EXISTS participanttype;")
