"""add-friendship-and-external-contact-table

Revision ID: 20251126_1225
Revises: 20251124_1639
Create Date: 2025-11-26 12:25:20.115365

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20251126_1225'
down_revision: Union[str, Sequence[str], None] = '20251124_1639'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('external_contact',
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('phone', sa.String(), nullable=True),
    sa.Column('photo_url', sa.String(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('friendship',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('contact_type', sa.Enum('user', 'external', name='contacttype'), nullable=False),
    sa.Column('friend_user_id', sa.UUID(), nullable=True),
    sa.Column('external_contact_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'accepted', 'rejected', name='friendshipstatus'), nullable=False),
    sa.ForeignKeyConstraint(['external_contact_id'], ['external_contact.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['friend_user_id'], ['user.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_friendship_external_contact_id'), 'friendship', ['external_contact_id'], unique=False)
    op.create_index(op.f('ix_friendship_friend_user_id'), 'friendship', ['friend_user_id'], unique=False)
    op.create_index(op.f('ix_friendship_user_id'), 'friendship', ['user_id'], unique=False)
    op.add_column('user', sa.Column('username', sa.String(length=30), nullable=False))
    op.add_column('user', sa.Column('photo_url', sa.String(), nullable=True))
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_column('user', 'photo_url')
    op.drop_column('user', 'username')
    op.drop_index(op.f('ix_friendship_user_id'), table_name='friendship')
    op.drop_index(op.f('ix_friendship_friend_user_id'), table_name='friendship')
    op.drop_index(op.f('ix_friendship_external_contact_id'), table_name='friendship')
    op.drop_table('friendship')
    op.drop_table('external_contact')
    # ### end Alembic commands ###
