"""add-status-to-user_friend

Revision ID: 20251125_2038
Revises: 20251125_1201
Create Date: 2025-11-25 20:38:46.387483

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20251125_2038'
down_revision: Union[str, Sequence[str], None] = '20251125_1201'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Use CASCADE to drop constraint and dependent objects so that we do not hit dependency errors as seen in the context
    op.execute('ALTER TABLE friend DROP CONSTRAINT IF EXISTS friend_friend_user_id_key CASCADE')
    op.drop_index(op.f('ix_friend_status'), table_name='friend')
    op.drop_constraint(op.f('uq_friend_friend_user_id'), 'friend', type_='unique')
    op.drop_index(op.f('ix_friend_friend_user_id'), table_name='friend')
    op.create_index(op.f('ix_friend_friend_user_id'), 'friend', ['friend_user_id'], unique=True)
    op.drop_column('friend', 'status')
    op.drop_constraint(op.f('user_username_key'), 'user', type_='unique')
    op.add_column('user_friend', sa.Column('status', sa.String(length=20), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_friend', 'status')
    op.create_unique_constraint(op.f('user_username_key'), 'user', ['username'], postgresql_nulls_not_distinct=False)
    op.add_column('friend', sa.Column('status', sa.VARCHAR(length=16), server_default=sa.text("'pending'::character varying"), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_friend_friend_user_id'), table_name='friend')
    op.create_index(op.f('ix_friend_friend_user_id'), 'friend', ['friend_user_id'], unique=False)
    op.create_unique_constraint(op.f('uq_friend_friend_user_id'), 'friend', ['friend_user_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_friend_status'), 'friend', ['status'], unique=False)
    # Use CASCADE here as well to restore the previous constraint and avoid problems
    op.execute('ALTER TABLE friend ADD CONSTRAINT friend_friend_user_id_key UNIQUE (friend_user_id)')
    # ### end Alembic commands ###
