"""make-friend-email-not-unique

Revision ID: 20251125_2058
Revises: 20251125_2054
Create Date: 2025-11-25 20:58:49.966296

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '20251125_2058'
down_revision: Union[str, Sequence[str], None] = '20251125_2054'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_friend_email'), table_name='friend')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_friend_email'), 'friend', ['email'], unique=True)
    # ### end Alembic commands ###
